### ISSUE TITLE
Sticky Footer: Tailwind CSS

### ISSUE THREAD

**Issue by drewclem** [drewclem/Colt#4]
The footer needs to be at the bottom of the window regardless of the amount of content displayed.  The site is styled with Tailwind css so they may have an easy fix in their documentation [here.](https://tailwindcss.com/docs/installation/)

![colt](https://user-images.githubusercontent.com/36208622/66520577-6ec79880-eab7-11e9-8a20-4940068f01bf.PNG)

**Comment by ynn1k** [comment]
ill look into it :)

**Comment by drewclem** [comment]
Much appreciated!

**Comment by Swayamsvk** [comment]
Can I work on this?

**Comment by drewclem** [comment]
@swayamsvk go for it

**Comment by amarjeetrao** [comment]
Hey i would like to look into this. May I?

**Comment by drewclem** [comment]
@amarjeetrao Absolutely!!

**Comment by raphaelcleto** [comment]
Hey! I've opened a pull request solving this issue. Could you check it please? https://github.com/drewclem/Colt/pull/5

**Comment by drewclem** [comment]
I believe my instructions may have been unclear. We need to place the footer at the bottom of the viewport when the content on the page does not extend past the viewport height.

For example, the /projectboard page is fine as is since the content extends beyond the viewport height. If you look at the /signin or /signup page the footer sits just below the input fields and it's instances like that where we need to force it to the bottom.

I apologize if my initial instructions were unclear. You dont' have to confine yourself to tailwind either. Some scoped css on the default.vue layout may do the trick with a min-height: calc(100vh - [height of the footer]

**Comment by ynn1k** [comment]
cant you just solve this by making the #app container a flex element of min-height: 100vh and add a margin-top: auto to the footer?
